version: '3'

services:
  db-postgres:
    image: postgres:12.2
    container_name: db-postgres
    environment:
      POSTGRES_DB: expense_manage_dev
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: